### ISSUE TITLE
请问有部署指南吗

### ISSUE THREAD

**Issue by zhjan33** [woodongwong/tvfix#2]

**Comment by woodongwong** [comment]
https://developers.cloudflare.com/workers/

**Comment by lukaschan** [comment]
小白不懂，请问可以部署到docker吗？有什么worker源推荐？

**Comment by zhjan33** [comment]
workers+自备域名，晚上9点，观看央视正常，但无线新闻等香港频道不停打转就是播放不出来，但同时段网页版电视匣播放正常。猜想能部署在本地机器效果会不会好很多呢

**Comment by zhjan33** [comment]
谢谢大佬题示，在CF部署好了，用自备域名算是可看，但香港的电视台卡得很，猜想本地软路由部署效果可能会好很多。但如何部署毫无头绪，大佬可否给 几个关键词让我百度下该如何部署？谢谢大佬

**Comment by woodongwong** [comment]
README 增加了部署示例。

**Comment by luii2020** [comment]
本地部署成功了，只能用ip加端口模式打开，不能生成m3u8,不如出个详细的cf教程生成自己域名的m3u8

**Comment by woodongwong** [comment]
> 本地部署成功了，只能用ip加端口模式打开，不能生成m3u8,不如出个详细的cf教程生成自己域名的m3u8

本地观看要域名干什么？

**Comment by luii2020** [comment]
异地看

**Comment by woodongwong** [comment]
> 本地部署成功了，只能用ip加端口模式打开，不能生成m3u8,不如出个详细的cf教程生成自己域名的m3u8

我没有富裕的的时间，如果您学会了如何配置，欢迎PR！
