### ISSUE TITLE
请问大佬，部署在CF，看电视的全部流量是不是全经过CF了，部署在路由器也是同样？

### ISSUE THREAD

**Issue by zhjan33** [woodongwong/tvfix#4]

**Comment by redrainl** [comment]
我是装在vps上的，感觉vps流量并没有增加。我理解本项目的目的是生成自定义域名的m3u播放链接，方式是做了请求播放地址的转换，数据流量还是走正常途径，地址请求的这一点数据才走cf。
但是现在直接用电视匣的域名加m3u无法播放吗？我怎么觉得好像以前用过直接用电视匣域名地址的播放源呢？

**Comment by woodongwong** [comment]
> 我是装在vps上的，感觉vps流量并没有增加。我理解本项目的目的是生成自定义域名的m3u播放链接，方式是做了请求播放地址的转换，数据流量还是走正常途径，地址请求的这一点数据才走cf。 但是现在直接用电视匣的域名加m3u无法播放吗？我怎么觉得好像以前用过直接用电视匣域名地址的播放源呢？

是这样的，电视侠后来将一些视频加密了，需要将key放到m3u8文件中，其实很简单，没几行代码。

**Comment by zhjan33** [comment]
我小白不懂，用win10做测试时发现没流量经过电脑有这疑问，谢谢大佬！
